version: '3.4'

services:
  microservice1.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  microservice2.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
