version: '3.4'

services:

  sqlserver:
   environment :
    - ACCEPT_EULA=Y
    - MSSQL_SA_PASSWORD=Password122*
   volumes:
    - sqlserver_staging_volume:/var/opt/mssql
   ports:
      - "1500:1433" 
  microservice1.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    ports:
      - "5000:80"
  microservice2.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    ports:
      - "5010:80"
volumes:
  sqlserver_staging_volume :
